"""users participant vehicle and policy tables

Revision ID: ba02e35839f3
Revises: 0e791bedf56b
Create Date: 2025-10-28 12:20:57.603825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba02e35839f3'
down_revision = '0e791bedf56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='participantgender'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('nationality', sa.String(length=32), nullable=False),
    sa.Column('occupation', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_participant_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_last_name'), ['last_name'], unique=False)

    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('license_plate', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_make'), ['make'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_model'), ['model'], unique=False)

    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.Enum('MOTOR', 'TRAVEL', 'MEDICAL', name='risktype'), nullable=False),
    sa.Column('usage_type', sa.Enum('PRIVATE', 'COMMERCIAL', name='usagetype'), nullable=False),
    sa.Column('coverage_type', sa.Enum('THIRD_PARTY', 'COMPREHENSIVE', name='coveragetype'), nullable=False),
    sa.Column('transaction_type', sa.Enum('NEW_BUSINESS', 'RENEWAL', 'CANCELLATION', 'CLAIM', 'PAYMENT', 'REFUND', 'OTHER', name='transactiontype'), nullable=False),
    sa.Column('transaction_branch', sa.Enum('KAIRABA', 'BRUSUBI', 'TALLINDING', 'BANJUL', 'BRIKAMA', 'SERREKUNDA', 'COASTAL_ROAD', name='transactionbranch'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('cover_period', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'CANCELLED', name='policystatus'), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_model'))
        batch_op.drop_index(batch_op.f('ix_vehicle_make'))

    op.drop_table('vehicle')
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_last_name'))
        batch_op.drop_index(batch_op.f('ix_participant_first_name'))
        batch_op.drop_index(batch_op.f('ix_participant_email'))

    op.drop_table('participant')
    # ### end Alembic commands ###
